### ISSUE TITLE
Suggestion: PlayerLightLevel Condition

### ISSUE THREAD

**Issue by Omanoctoa** [BerndiVader/mmCustomSkills26#52]
Hello!
I've been trying to set up a system where players must stay out of shadows. Would it be possible to add a Condition TargetLightLevel (range) to check the light level of a player or entity's location? Specifically players, but I imagine it would have great benefit to other target types as well. The TLL condition would work exactly like the basic LightLevel condition, apart from checking the target's light-level instead of the caster's.

Thanks for your consideration.

**Comment by BerndiVader** [comment]
Hello Omanoctoa!

There already is a lightlevel condition supplied by mythicmobs. It checks the lightlevel of the block. Take a look here: http://www.mythicmobs.net/manual/doku.php/conditions/start

If you want the condition checked for the target use `TargetConditions`. Example:

```
example_mob:
  Type: cow
  Skills:
    - skill{s=example_skill} @trigger ~onInteract

example_skill:
  Conditions:
    - lightlevel{level=>2}
  TargetCondtions:
    - lightlevel{level=>2}
  Skills:
    - message{msg="hi!"}
```

Please note that for TargetConditions the trigger of the skill matters. For example, if you use in @self in your mob as target the TargetConditions will be used for the mob itself. If you use @target in your mob the TargetConditions will use the target of the mob. If you use @trigger the entity that triggered the skill is used, eg: @trigger ~onDamaged means the entity that damaged the mob is used etc....
