### ISSUE TITLE
Add setRandomMobHealth for monsters

### ISSUE THREAD

**Issue by madtomic** [BerndiVader/mmCustomSkills26#67]
I'm looking for a way to give my monster a random health when it spawns.

Please consider to add this. setRandomMobHealth

Thanks

**Comment by BerndiVader** [comment]
Hello madtomic! Thank you for your suggestion and sorry for my late response, im pretty busy at the moment. You already can do this. Not within a single mechanic but therefor more customizable. Here is an example how it can be done:

```
potato1:
  Type: zombie
  Health: 100
  AITargetSelectors:
  - 0 clear
  Skills:
  - sunresist ~onSpawn
  - skill{s=random_health} @self ~onSpawn

random_health:
  Skills:
  - mathex{eval="10+rnd(20)";store=<mob.meta.rnd_health>}
  - setnbt{nbt="{Health:<mob.meta.rnd_health>}"}
  - delay 1
  - message{msg="<mob.hp>"} @world
```

Create a random integer with mathex and store it into the scoreboard or, like in the example, into the metadata. Next use setnbt mechanic to change the entitys health tag to the stored value and you are done. Greetings, Berndi
